---
- name: Sol1 packages repository
  when: sol1_packages_repo_enabled
  block:
    - name: Remove old dearmored keyring if present
      ansible.builtin.file:
        path: /usr/share/keyrings/sol1-archive-keyring.gpg
        state: absent

    - name: Download Sol1 package signing key
      ansible.builtin.get_url:
        url: https://packages.sol1.net/packages.key
        dest: /usr/share/keyrings/sol1-archive-keyring.asc
        mode: "0644"
      environment:
        http_proxy: "{{ network_settings.proxies.http | default('') }}"
        https_proxy: "{{ network_settings.proxies.https | default('') }}"

    - name: Add packages.sol1.net repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/sol1.sources
        owner: root
        group: root
        mode: "0644"
        content: |
          Types: deb
          URIs: https://packages.sol1.net
          Suites: {{ sol1_packages_repo_debian_suite }}
          Components: main
          Signed-By: /usr/share/keyrings/sol1-archive-keyring.asc
      register: sol1_sources

    - name: Update apt cache with Sol1 repo
      ansible.builtin.apt:
        update_cache: true
      when: sol1_sources.changed
